name: 'Run specified test workflow'
description: 'Setup to run specified test from workflow'

inputs:
  image:
    type: string
  artifact_name:
    type: string

runs:
  using: 'composite'
  steps:
    - name: Setup Environment
      uses: deitch/actions-test/.github/actions/setup-environment@master
      with:
        image: ${{ inputs.image }}
        artifact_name: ${{ inputs.artifact_name }}
    - name: Report images
      run: docker image ls
      shell: bash
