name: TestMultiArch
on:
  repository_dispatch:
    types: [multiarch]

jobs:
  report:
    name: Report
    runs-on: ubuntu-latest
    steps:
    - name: ref
      run: echo ${{ github.ref }}
    - name: event_name
      run: echo ${{ github.event_name }}
    - name: uname
      run: uname -a
    - name: osrelease
      run: cat /etc/os-release

