name: PR build
on:
  pull_request_target:
    branches:
      - "master"
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clear repository
        run: |
          sudo rm -fr "$GITHUB_WORKSPACE" && mkdir "$GITHUB_WORKSPACE"
          rm -fr ~/.linuxkit
          docker system prune --all --force --volumes
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: report
        run: |
          echo github.sha ${{ github.sha }}
          git log


